[package]
name = "yolo_core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
uuid = { version = "1.16", features = ["v4"] }
rust_decimal = { version = "1.37", features = ["macros"] }
thiserror = "2.0.12"
